name: clippy
description: Access system clipboard in Dart (Server & Browser).
version: 1.0.0
homepage: https://github.com/andresaraujo/clippy
author: Andres Araujo <a.araujo.azua@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  path: ^1.4.2

dev_dependencies:
  test: ^1.3.0
