name: clippy
description: Access system clipboard in Dart (Server & Browser).
version: 0.1.0
homepage: https://github.com/andresaraujo/clippy
author: Andres Araujo <a.araujo.azua@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.2

dev_dependencies:
  test: ^0.12.0
  browser: any
